formatter: markdown table

sections:
  hide-all: true
  show:
    # - header
    - providers
    - inputs
    - outputs

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->

    {{ .Content }}

    <!-- END_TF_DOCS -->

# output-values:
#   enabled: false
#   from: "outputs.tf"

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  escape: true
  indent: 2
  required: true
  sensitive: true
  type: true
