on:
  push:
    branches:
      - main

name: release
jobs:
  release:
    uses: padok-team/github-workflows/.github/workflows/release.yml@c40746aeaaad9e67783f9ba0cd7ef514209c9621 # v1
    with:
      release-type: "terraform-module"
      update-major-minor-tags: true
