on:
  push:
    branches:
      - main

name: release
jobs:
  release:
    uses: padok-team/github-workflows/.github/workflows/release.yml@9f83288283a008c206318c2d45ec2c69f13349c3 # v1
    with:
      release-type: "terraform-module"
      update-major-minor-tags: true
