on:
  pull_request:
    branches:
      - main
name: terraform-quality
jobs:
  terraform-quality:
    uses: padok-team/github-workflows/.github/workflows/terraform-quality.yml@9f83288283a008c206318c2d45ec2c69f13349c3 # v1
    with:
      checkov_skip_path: "examples/"
      checkov_baseline: ".checkov.baseline"
