on:
  pull_request:
    branches:
      - main
name: terraform-quality
jobs:
  terraform-quality:
    uses: padok-team/github-workflows/.github/workflows/terraform-quality.yml@c40746aeaaad9e67783f9ba0cd7ef514209c9621 # v1
    with:
      checkov_skip_path: "examples/"
      checkov_baseline: ".checkov.baseline"
